"""Dados consolidados de pesquisa de trajetória para os 74 candidatos competitivos do Senado.

Inclui cargos não eletivos (secretarias, ministérios, diretorias), mandatos anteriores
a 2006 (fora da cobertura padrão do TSE) e áreas/temáticas principais.
"""

PESQUISA_SENADO_74 = {
    "10002548046": {  # Gladson Camelí (PP/AC)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Engenheiro civil da iniciativa privada e companhias de saneamento",
        "Pasta ou área": "Infraestrutura / Saneamento",
        "Período": "2000-2006",
        "Temática principal": "Infraestrutura de transportes, saneamento básico, desenvolvimento regional",
        "Fonte da informação": "Câmara dos Deputados / Governo do Acre",
        "Observações": "Eleito deputado federal em 2006 e 2010; senador em 2014; governador em 2018 e 2022",
    },
    "10002536441": {  # Jorge Viana (PT/AC)
        "Teve mandato antes de 2006?": "Prefeito de Rio Branco (1993-1997); Governador do Acre (1999-2007)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente da ApexBrasil",
        "Pasta ou área": "Comércio Exterior / Atração de Investimentos",
        "Período": "2023-presente",
        "Temática principal": "Desenvolvimento sustentável amazônico, meio ambiente e comércio exterior",
        "Fonte da informação": "Senado Federal / ApexBrasil",
        "Observações": "Engenheiro florestal de formação; senador de 2011 a 2019",
    },
    "10002533895": {  # Mara Rocha (REPUBLICANOS/AC)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Jornalista e apresentadora de televisão",
        "Pasta ou área": "Comunicação Social",
        "Período": "2000-2018",
        "Temática principal": "Agricultura, segurança pública e infraestrutura regional",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputada federal eleita em 2018",
    },
    "20002553272": {  # Arthur Lira (PP/AL)
        "Teve mandato antes de 2006?": "Vereador de Maceió (1993-1999); Deputado estadual AL (1999-2010)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente da Câmara dos Deputados",
        "Pasta ou área": "Poder Legislativo",
        "Período": "2021-2025",
        "Temática principal": "Agropecuária, reforma tributária, gestão fiscal e orçamento",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputado federal desde 2011; presidiu a Câmara por dois biênios consecutivos",
    },
    "20002553711": {  # Marina JHC (PSDB/AL)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Advogada e empresária",
        "Pasta ou área": "Setor Privado / Ações Sociais",
        "Período": "-",
        "Temática principal": "Empreendedorismo, desenvolvimento comunitário e infância",
        "Fonte da informação": "TSE / Registro público",
        "Observações": "Esposa do prefeito de Maceió JHC",
    },
    "40002542686": {  # Capitão Alberto Neto (PL/AM)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Capitão da Polícia Militar do Amazonas; Comandante de Policiamento Comunitário",
        "Pasta ou área": "Segurança Pública",
        "Período": "2008-2018",
        "Temática principal": "Segurança pública, defesa da Zona Franca de Manaus e combate à corrupção",
        "Fonte da informação": "Câmara dos Deputados / PM-AM",
        "Observações": "Deputado federal eleito em 2018 e 2022",
    },
    "30002530071": {  # Rayssa Furlan (PODE/AP)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretária Municipal de Mobilização e Participação Popular de Macapá",
        "Pasta ou área": "Mobilização Social / Saúde",
        "Período": "2021-2022",
        "Temática principal": "Saúde pública (médica), assistência social e políticas para a família",
        "Fonte da informação": "Prefeitura de Macapá / Diário Oficial",
        "Observações": "Esposa do prefeito de Macapá Dr. Furlan",
    },
    "50002536321": {  # Rui Costa (PT/BA)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Relações Institucionais da BA; Secretário-Chefe da Casa Civil da BA; Ministro-Chefe da Casa Civil da Presidência",
        "Pasta ou área": "Casa Civil / Articulação Governamental",
        "Período": "2007-2010 (SRI-BA), 2012-2014 (Casa Civil BA), 2023-presente (Casa Civil Federal)",
        "Temática principal": "Gestão governamental, grandes obras e infraestrutura (PAC), saneamento e saúde",
        "Fonte da informação": "Presidência da República / Governo da Bahia / Câmara dos Deputados",
        "Observações": "Governador da Bahia por dois mandatos (2015-2022)",
    },
    "60002540753": {  # Capitão Wagner (UNIÃO/CE)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Capitão da Polícia Militar do Ceará; Secretário Municipal de Saúde de Maracanaú",
        "Pasta ou área": "Segurança Pública / Saúde",
        "Período": "1999-2011 (PM-CE), 2023-2024 (Saúde Maracanaú)",
        "Temática principal": "Segurança pública, gestão da saúde pública e combate à criminalidade",
        "Fonte da informação": "Câmara dos Deputados / Prefeitura de Maracanaú",
        "Observações": "Vereador em 2012, deputado estadual em 2014, deputado federal em 2018",
    },
    "60002542476": {  # Luizianne Lins (REDE/CE)
        "Teve mandato antes de 2006?": "Vereadora de Fortaleza (1997-2002); Deputada estadual CE (2003-2004); Prefeita de Fortaleza (2005-2012)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Professora Universitária da Universidade Federal do Ceará (UFC)",
        "Pasta ou área": "Ensino Superior e Comunicação",
        "Período": "1995-presente (UFC)",
        "Temática principal": "Educação, direitos humanos, igualdade de gênero e habitação social",
        "Fonte da informação": "Câmara dos Deputados / UFC",
        "Observações": "Jornalista e professora; deputada federal desde 2015",
    },
    "70002552934": {  # Bia Kicis (PL/DF)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Subprocuradora-Geral do Distrito Federal",
        "Pasta ou área": "Procuradoria-Geral do DF (Advocacia Pública)",
        "Período": "1992-2016",
        "Temática principal": "Direito constitucional, reformas jurídicas e pautas conservadoras",
        "Fonte da informação": "PGDF / Câmara dos Deputados",
        "Observações": "Presidiu a CCJC da Câmara dos Deputados em 2021",
    },
    "70002552490": {  # Erika Kokay (PT/DF)
        "Teve mandato antes de 2006?": "Deputada distrital DF (2003-2010)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Bancária da Caixa Econômica Federal; Presidente do Sindicato dos Bancários e da CUT-DF",
        "Pasta ou área": "Movimento Sindical / Direitos Humanos",
        "Período": "1982-2002",
        "Temática principal": "Direitos humanos, proteção aos trabalhadores, saúde mental e minorias",
        "Fonte da informação": "Câmara dos Deputados / CUT-DF",
        "Observações": "Deputada federal pelo DF desde 2011",
    },
    "70002552936": {  # Michelle Bolsonaro (PL/DF)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Primeira-dama do Brasil; Presidente do Conselho do Programa Pátria Voluntária; Presidente do PL Mulher",
        "Pasta ou área": "Voluntariado, Acessibilidade e Assistência Social",
        "Período": "2019-2022 (Governo Federal), 2023-presente (PL Mulher)",
        "Temática principal": "Inclusão de pessoas com deficiência, Libras, doenças raras e pautas da família",
        "Fonte da informação": "Governo Federal / PL",
        "Observações": "Liderança nacional do movimento conservador e voluntariado",
    },
    "80002553269": {  # Maguinha Malta (PL/ES)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Publicitária e comunicadora",
        "Pasta ou área": "Comunicação e Marketing",
        "Período": "Setor privado",
        "Temática principal": "Comunicação, defesa da infância, combate ao abuso infantil e valores da família",
        "Fonte da informação": "TSE / Registro público",
        "Observações": "Esposa do senador Magno Malta",
    },
    "80002551370": {  # Renato Casagrande (PSB/ES)
        "Teve mandato antes de 2006?": "Deputado estadual ES (1991-1995); Vice-governador ES (1995-1999); Deputado federal (1999-2003)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Agricultura do ES; Secretário Municipal de Meio Ambiente de Serra",
        "Pasta ou área": "Agricultura / Meio Ambiente",
        "Período": "1995-1999 (Seag-ES), 2003-2004 (Serra)",
        "Temática principal": "Gestão fiscal eficiente, sustentabilidade e combate a mudanças climáticas, educação",
        "Fonte da informação": "Governo do ES / Câmara dos Deputados",
        "Observações": "Senador de 2007 a 2010; governador do ES (2011-2014, 2019-presente)",
    },
    "80002551368": {  # Rose de Freitas (MDB/ES)
        "Teve mandato antes de 2006?": "Deputada estadual ES (1983-1987); Deputada federal constituinte (1987-1991, 1995-1999, 2003-2015)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Jornalista e radialista",
        "Pasta ou área": "Comunicação",
        "Período": "-",
        "Temática principal": "Orçamento público (presidiu a CMO), defesa dos direitos da mulher e infraestrutura capixaba",
        "Fonte da informação": "Senado Federal / Câmara dos Deputados",
        "Observações": "Senadora de 2015 a 2023",
    },
    "80002552692": {  # Sergio Meneguelli (PSD/ES)
        "Teve mandato antes de 2006?": "Vereador de Colatina (1983-2004, 2009-2016)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Prefeito de Colatina",
        "Pasta ou área": "Gestão Municipal",
        "Período": "2017-2020",
        "Temática principal": "Zeladoria urbana, paisagismo, transparência e controle de gastos municipais",
        "Fonte da informação": "Assembleia ES / Prefeitura de Colatina",
        "Observações": "Deputado estadual mais votado da história do ES em 2022",
    },
    "90002540997": {  # Gracinha Caiado (UNIÃO/GO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente de Honra da Organização das Voluntárias de Goiás (OVG) e Coordenadora do Gabinete de Políticas Sociais",
        "Pasta ou área": "Políticas Sociais e Combate à Vulnerabilidade",
        "Período": "2019-presente",
        "Temática principal": "Assistência social, proteção à primeira infância e combate à extrema pobreza",
        "Fonte da informação": "Governo de Goiás / OVG",
        "Observações": "Advogada; esposa do governador Ronaldo Caiado",
    },
    "90002543556": {  # Gustavo Gayer (PL/GO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Professor de idiomas, comunicador e empresário",
        "Pasta ou área": "Educação / Comunicação",
        "Período": "Setor privado",
        "Temática principal": "Liberdade de expressão, pautas educacionais e conservadorismo",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputado federal eleito em 2022",
    },
    "100002548011": {  # Lahesio Bonfim (NOVO/MA)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Médico do Programa Saúde da Família e diretor clínico",
        "Pasta ou área": "Saúde Pública",
        "Período": "2004-2016",
        "Temática principal": "Saúde pública, austeridade na gestão pública e agronegócio",
        "Fonte da informação": "Prefeitura de São Pedro dos Crentes / CRM-MA",
        "Observações": "Prefeito de São Pedro dos Crentes (2017-2022); segundo colocado ao governo do MA em 2022",
    },
    "100002549583": {  # Roseana Sarney (MDB/MA)
        "Teve mandato antes de 2006?": "Deputada federal (1991-1994, 2023-); Governadora do Maranhão (1995-2002, 2009-2014); Senadora (2003-2009)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretária de Assuntos Extraordinários do MA; Chefe de Gabinete da Casa Civil da Presidência",
        "Pasta ou área": "Casa Civil / Articulação Legislativa",
        "Período": "1985-1990, 2025",
        "Temática principal": "Desenvolvimento socioeconômico do Maranhão, saneamento e programas sociais",
        "Fonte da informação": "FGV CPDOC / Câmara dos Deputados",
        "Observações": "Socióloga de formação",
    },
    "130002554332": {  # Aécio Neves (PSDB/MG)
        "Teve mandato antes de 2006?": "Deputado federal (1987-2002); Presidente da Câmara (2001-2002); Governador de Minas Gerais (2003-2010)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário Particular da Presidência da República; Diretor da Caixa Econômica do Estado de Minas Gerais",
        "Pasta ou área": "Administração Pública / Finanças",
        "Período": "1985 (Presidência), 1985-1986 (Caixa MG)",
        "Temática principal": "Reforma administrativa ('Choque de Gestão'), pacto federativo e política externa",
        "Fonte da informação": "FGV CPDOC / Câmara dos Deputados",
        "Observações": "Senador por MG de 2011 a 2019; candidato à Presidência da República em 2014",
    },
    "130002551786": {  # Domingos Sávio (PL/MG)
        "Teve mandato antes de 2006?": "Prefeito de Divinópolis (2001-2004); Vereador de Divinópolis (1989-1992); Deputado estadual MG (1995-2000, 2007-2010)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Médico Veterinário e produtor rural; Presidente do Sindicato Rural e de cooperativas de crédito",
        "Pasta ou área": "Agropecuária / Cooperativismo",
        "Período": "1986-1994",
        "Temática principal": "Agronegócio, defesa sanitária animal e vegetal, cooperativismo e municípios",
        "Fonte da informação": "Câmara dos Deputados / Assembleia MG",
        "Observações": "Deputado federal desde 2011",
    },
    "130002548381": {  # Marcelo Aro (PP/MG)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Casa Civil de Minas Gerais",
        "Pasta ou área": "Casa Civil",
        "Período": "2023-2025 (Governo Zema)",
        "Temática principal": "Articulação institucional, gestão governamental e doenças raras",
        "Fonte da informação": "Governo de Minas Gerais / Câmara dos Deputados",
        "Observações": "Vereador de BH em 2012; deputado federal de 2015 a 2023",
    },
    "130002550560": {  # Marília Campos (PT/MG)
        "Teve mandato antes de 2006?": "Vereadora de Contagem (2001-2004); Prefeita de Contagem (2005-2012, 2021-)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Psicóloga e dirigente do Sindicato dos Bancários de Belo Horizonte",
        "Pasta ou área": "Movimento Sindical / Saúde Mental",
        "Período": "1988-2000",
        "Temática principal": "Desenvolvimento urbano e mobilidade da Grande BH, saúde e assistência social",
        "Fonte da informação": "Prefeitura de Contagem / Assembleia MG",
        "Observações": "Deputada estadual de 2015 a 2020",
    },
    "120002535769": {  # Capitão Contar (PL/MS)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Capitão do Exército Brasileiro (Oficial de Artilharia - Aman)",
        "Pasta ou área": "Forças Armadas / Defesa",
        "Período": "2002-2018",
        "Temática principal": "Defesa nacional, segurança de fronteiras, agronegócio e combate à corrupção",
        "Fonte da informação": "Exército Brasileiro / Assembleia MS",
        "Observações": "Deputado estadual mais votado de MS em 2018; disputou 2º turno para governador em 2022",
    },
    "120002535764": {  # Reinaldo Azambuja (PL/MS)
        "Teve mandato antes de 2006?": "Prefeito de Maracaju (1997-2004)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Produtor rural e pecuarista; Presidente do Sindicato Rural de Maracaju",
        "Pasta ou área": "Agropecuária",
        "Período": "1993-1996",
        "Temática principal": "Agronegócio, responsabilidade fiscal, logística e integração regional (Rota Bioceânica)",
        "Fonte da informação": "Governo de MS / Câmara dos Deputados",
        "Observações": "Deputado federal (2007-2014); Governador de MS por dois mandatos (2015-2022)",
    },
    "110002552698": {  # Janaina Riva (MDB/MT)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Empresária e administradora",
        "Pasta ou área": "Setor privado",
        "Período": "-",
        "Temática principal": "Direitos da mulher, infraestrutura regional de MT e apoio ao agronegócio e municípios",
        "Fonte da informação": "Assembleia Legislativa de Mato Grosso",
        "Observações": "Deputada estadual de MT desde 2015; presidiu a Mesa Diretora da ALMT",
    },
    "110002551966": {  # Mauro Mendes (UNIÃO/MT)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente da Federação das Indústrias no Estado de Mato Grosso (FIEMT); Prefeito de Cuiabá (2013-2016)",
        "Pasta ou área": "Indústria e Desenvolvimento Econômico",
        "Período": "2007-2010 (FIEMT)",
        "Temática principal": "Gestão fiscal rigorosa, infraestrutura rodoviária e ferrovias, industrialização do agro",
        "Fonte da informação": "Governo de Mato Grosso / FIEMT",
        "Observações": "Empresário do setor metalúrgico; Governador de MT desde 2019",
    },
    "140002538404": {  # Celso Sabino (PDT/PA)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministro de Estado do Turismo; Secretário de Estado de Trabalho, Emprego e Renda do Pará",
        "Pasta ou área": "Turismo / Trabalho e Renda",
        "Período": "2012-2013 (Seter-PA), 2023-presente (Ministério do Turismo)",
        "Temática principal": "Promoção do turismo sustentável, capacitação profissional e obras preparatórias para a COP 30",
        "Fonte da informação": "Ministério do Turismo / Câmara dos Deputados",
        "Observações": "Advogado e auditor fiscal; deputado federal desde 2019",
    },
    "140002550780": {  # Chicão (UNIÃO/PA)
        "Teve mandato antes de 2006?": "Prefeito de Ananindeua (1993-1996); Vereador de Ananindeua (1989-1992)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado de Obras Públicas do Pará (Sedop); Presidente da Alepa",
        "Pasta ou área": "Obras Públicas e Habitação",
        "Período": "2007-2010 (Sedop-PA)",
        "Temática principal": "Infraestrutura urbana, saneamento básico, habitação e obras de transporte",
        "Fonte da informação": "Assembleia Legislativa do Pará",
        "Observações": "Engenheiro civil; presidiu a Alepa em mandatos consecutivos",
    },
    "140002544855": {  # Delegado Éder Mauro (PL/PA)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Delegado da Polícia Civil do Pará; Diretor de Polícia Metropolitana",
        "Pasta ou área": "Segurança Pública / Polícia Judiciária",
        "Período": "1984-2014 (Polícia Civil PA)",
        "Temática principal": "Segurança pública, endurecimento penal e combate ao tráfico de drogas",
        "Fonte da informação": "Polícia Civil do Pará / Câmara dos Deputados",
        "Observações": "Deputado federal desde 2015",
    },
    "140002550779": {  # Helder Barbalho (MDB/PA)
        "Teve mandato antes de 2006?": "Vereador de Ananindeua (2001-2003); Deputado estadual PA (2003-2005); Prefeito de Ananindeua (2005-2013)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministro da Integração Nacional; Ministro-Chefe da Secretaria de Portos",
        "Pasta ou área": "Integração Nacional / Portos",
        "Período": "2015-2016 (Portos), 2016-2018 (Integração)",
        "Temática principal": "Bioeconomia amazônica, transição climática (liderança da COP 30 em Belém) e obras hídricas",
        "Fonte da informação": "Diário Oficial da União / Governo do Pará",
        "Observações": "Administrador de empresas; Governador do Pará desde 2019",
    },
    "150002549793": {  # Joao Azevêdo (PSB/PB)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Infraestrutura, Recursos Hídricos, Meio Ambiente e Ciência da PB; Secretário de Planejamento de João Pessoa",
        "Pasta ou área": "Infraestrutura, Recursos Hídricos e Meio Ambiente",
        "Período": "2007-2010 (João Pessoa), 2011-2018 (Governo PB)",
        "Temática principal": "Segurança hídrica (Transposição do São Francisco), energias renováveis e infraestrutura rodoviária",
        "Fonte da informação": "Governo da Paraíba",
        "Observações": "Engenheiro civil e professor do IFPB; Governador da Paraíba desde 2019",
    },
    "170002547771": {  # Marília Arraes (PDT/PE)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretária Municipal de Juventude e Qualificação Profissional do Recife",
        "Pasta ou área": "Juventude e Qualificação Profissional",
        "Período": "2013-2014",
        "Temática principal": "Qualificação para o emprego, direitos trabalhistas, assistência social e políticas para mulheres",
        "Fonte da informação": "Prefeitura do Recife / Câmara dos Deputados",
        "Observações": "Vereadora do Recife (2009-2018); Deputada federal (2019-2022)",
    },
    "180002533964": {  # Júlio Cesar (PSD/PI)
        "Teve mandato antes de 2006?": "Prefeito de Guadalupe PI (1989-1992); Deputado federal (1995-1999, 2003-)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Agricultura, Abastecimento e Recursos Hídricos do Piauí",
        "Pasta ou área": "Agricultura e Recursos Hídricos",
        "Período": "1999-2001",
        "Temática principal": "Pacto federativo, finanças municipais (coordena bancada municipalista) e irrigação",
        "Fonte da informação": "Câmara dos Deputados / Governo do Piauí",
        "Observações": "Advogado e agropecuarista; deputado federal de longa trajetória",
    },
    "160002547963": {  # Alexandre Curi (REPUBLICANOS/PR)
        "Teve mandato antes de 2006?": "Vereador de Curitiba (2001-2002); Deputado estadual PR (2003-presente)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Primeiro-Secretário e Presidente da Assembleia Legislativa do Paraná (Alep)",
        "Pasta ou área": "Poder Legislativo",
        "Período": "2003-presente",
        "Temática principal": "Municipalismo paranaense, infraestrutura de ligação e desenvolvimento regional",
        "Fonte da informação": "Assembleia Legislativa do Paraná",
        "Observações": "Deputado estadual reeleito consecutivamente desde 2002",
    },
    "160002547661": {  # Deltan Dallagnol (NOVO/PR)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Procurador da República (Ministério Público Federal); Coordenador da Força-Tarefa Lava Jato",
        "Pasta ou área": "Ministério Público Federal",
        "Período": "2003-2021 (MPF)",
        "Temática principal": "Combate à corrupção, reforma penal e processual, integridade na gestão pública",
        "Fonte da informação": "MPF / Câmara dos Deputados",
        "Observações": "Deputado federal eleito em 2022 mais votado do Paraná",
    },
    "160002547660": {  # Filipe Barros (PL/PR)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Advogado e líder de movimentos civis",
        "Pasta ou área": "Advocacia",
        "Período": "Setor privado",
        "Temática principal": "Liberdade econômica, combate ao crime, pautas da família e agronegócio paranaense",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Vereador de Londrina em 2016; deputado federal desde 2019 (líder da oposição)",
    },
    "160002547656": {  # Gleisi Hoffmann (PT/PR)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministra-Chefe da Casa Civil da Presidência; Diretora Financeira da Itaipu Binacional; Secretária de Estado da Reestruturação Administrativa MS",
        "Pasta ou área": "Casa Civil / Finanças e Energia",
        "Período": "2003-2006 (Itaipu), 2011-2014 (Casa Civil)",
        "Temática principal": "Articulação de governo, programas de transferência de renda, energia e orçamento",
        "Fonte da informação": "Presidência da República / Câmara dos Deputados",
        "Observações": "Senadora da República (2011-2019); Presidente Nacional do PT",
    },
    "190002548141": {  # Benedita da Silva (PT/RJ)
        "Teve mandato antes de 2006?": "Vereadora do RJ (1983-1986); Deputada federal constituinte (1987-1994); Senadora (1995-1998); Vice-governadora e Governadora do RJ (1999-2003)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministra da Assistência e Promoção Social; Secretária de Estado de Assistência Social e Direitos Humanos RJ",
        "Pasta ou área": "Assistência Social e Direitos Humanos",
        "Período": "2003-2004 (Ministério), 2007-2010 (Governo RJ)",
        "Temática principal": "Igualdade racial, direitos das mulheres, trabalhadoras domésticas, cultura e assistência social",
        "Fonte da informação": "FGV CPDOC / Câmara dos Deputados",
        "Observações": "Primeira mulher negra a ocupar os cargos de senadora e governadora no Brasil",
    },
    "190002542888": {  # Carlos Jordy (PL/RJ)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Servidor público municipal e ativista político",
        "Pasta ou área": "Gestão Municipal",
        "Período": "2012-2016",
        "Temática principal": "Segurança pública, liberdades individuais e pautas conservadoras",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Vereador de Niterói em 2016; deputado federal desde 2019",
    },
    "190002550184": {  # Marcelo Crivella (REPUBLICANOS/RJ)
        "Teve mandato antes de 2006?": "Senador RJ (2003-2017); Prefeito do Rio de Janeiro (2017-2020)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministro de Estado da Pesca e Aquicultura",
        "Pasta ou área": "Pesca e Aquicultura",
        "Período": "2012-2014",
        "Temática principal": "Desenvolvimento do setor pesqueiro, obras de infraestrutura e amparo aos idosos",
        "Fonte da informação": "Presidência da República / Câmara dos Deputados",
        "Observações": "Engenheiro civil, escritor e bispo licenciado",
    },
    "190002548145": {  # Pedro Paulo (PSD/RJ)
        "Teve mandato antes de 2006?": "Deputado estadual RJ (2003-2007)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário Chefe da Casa Civil do RJ; Secretário Executivo de Coordenação de Governo do Rio; Secretário Municipal de Fazenda e Planejamento RJ",
        "Pasta ou área": "Fazenda, Planejamento e Gestão Pública",
        "Período": "2010-2014 (Casa Civil), 2015-2016 (Coordenação), 2021-2022 (Fazenda)",
        "Temática principal": "Equilíbrio fiscal, desregulamentação econômica, planejamento urbano e investimentos públicos",
        "Fonte da informação": "Prefeitura do Rio de Janeiro / Câmara dos Deputados",
        "Observações": "Economista de formação; deputado federal desde 2011",
    },
    "200002534447": {  # Cel. Hélio (PL/RN)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Coronel da Polícia Militar do Rio Grande do Norte; Subcomandante Geral da PM-RN",
        "Pasta ou área": "Segurança Pública",
        "Período": "Carreira militar até 2020",
        "Temática principal": "Segurança pública, policiamento ostensivo e combate às facções no RN",
        "Fonte da informação": "Polícia Militar do RN",
        "Observações": "Oficial da reserva da PM-RN",
    },
    "200002533843": {  # Rafael Motta (PDT/RN)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário Municipal de Esporte e Lazer de Natal",
        "Pasta ou área": "Esporte e Juventude",
        "Período": "2023-2024",
        "Temática principal": "Juventude, transição para energias renováveis (eólica/solar no RN) e turismo",
        "Fonte da informação": "Prefeitura de Natal / Câmara dos Deputados",
        "Observações": "Engenheiro de produção; deputado federal de 2015 a 2023",
    },
    "220002539995": {  # Bruno Scheid (PL/RO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Empresário e produtor rural",
        "Pasta ou área": "Agronegócio",
        "Período": "Setor privado",
        "Temática principal": "Agronegócio rondoniense, regularização fundiária e infraestrutura logística",
        "Fonte da informação": "TSE / Registro público",
        "Observações": "Produtor rural no interior de Rondônia",
    },
    "220002539996": {  # Dr. Fernando Máximo (PL/RO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Saúde de Rondônia (Sesau-RO)",
        "Pasta ou área": "Saúde",
        "Período": "2019-2022",
        "Temática principal": "Saúde pública, cirurgias eletivas, interiorização do atendimento médico e hospitais",
        "Fonte da informação": "Governo de Rondônia / Câmara dos Deputados",
        "Observações": "Médico cirurgião geral; deputado federal eleito em 2022 como o mais votado de RO",
    },
    "220002547310": {  # Mariana Carvalho (REPUBLICANOS/RO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Médica, advogada; Vereadora de Porto Velho (2009-2012); Deputada federal (2015-2023)",
        "Pasta ou área": "Saúde e Direitos da Mulher",
        "Período": "-",
        "Temática principal": "Saúde pública, defesa da mulher e investimentos federais para municípios rondonienses",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Segunda-secretária da Mesa Diretora da Câmara dos Deputados (2017-2019)",
    },
    "220002547309": {  # Silvia Cristina (PP/RO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Jornalista e radialista; Vereadora de Ji-Paraná (2013-2018)",
        "Pasta ou área": "Saúde Oncológica e Comunicação",
        "Período": "-",
        "Temática principal": "Tratamento oncológico (liderança na instalação do Hospital de Amor em RO), saúde e acessibilidade",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputada federal desde 2019",
    },
    "230002549845": {  # Helena Lima (PSD/RR)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Advogada e empresária",
        "Pasta ou área": "Setor privado",
        "Período": "-",
        "Temática principal": "Desenvolvimento sustentável de Roraima, integração energética e geração de empregos",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputada federal eleita em 2022",
    },
    "230002534804": {  # Nicoletti (PL/RR)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Policial Rodoviário Federal (PRF)",
        "Pasta ou área": "Segurança Pública / Trânsito Rodoviário",
        "Período": "2006-2018",
        "Temática principal": "Segurança pública, controle de fronteiras em Roraima e fortalecimento das forças policiais",
        "Fonte da informação": "PRF / Câmara dos Deputados",
        "Observações": "Deputado federal desde 2019",
    },
    "230002553006": {  # Teresa Surita (MDB/RR)
        "Teve mandato antes de 2006?": "Deputada federal (1991-1994, 2011-2012); Prefeita de Boa Vista (1993-1996, 2001-2006, 2013-2020)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretária Nacional de Programas Urbanos do Ministério das Cidades",
        "Pasta ou área": "Cidades e Desenvolvimento Urbano",
        "Período": "2009-2010",
        "Temática principal": "Políticas públicas para a primeira infância (Boa Vista como 'Capital da Primeira Infância'), educação infantil e urbanismo",
        "Fonte da informação": "FGV CPDOC / Ministério das Cidades",
        "Observações": "Prefeita de Boa Vista por cinco mandatos",
    },
    "210002533581": {  # Manuela D'Ávila (PSOL/RS)
        "Teve mandato antes de 2006?": "Vereadora de Porto Alegre (2005-2006); Deputada federal (2007-2015); Deputada estadual RS (2015-2019)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente do Instituto E Se Fosse Você?",
        "Pasta ou área": "Direitos Humanos, Juventude e Comunicação Digital",
        "Período": "2019-presente",
        "Temática principal": "Direitos das mulheres, combate à desinformação e violência política de gênero, educação",
        "Fonte da informação": "Câmara dos Deputados / Instituto E Se Fosse Você",
        "Observações": "Jornalista e escritora; candidata a vice-presidente da República em 2018",
    },
    "210002547819": {  # Marcel van Hattem (NOVO/RS)
        "Teve mandato antes de 2006?": "Vereador de Dois Irmãos RS (2005-2008)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Jornalista e cientista político",
        "Pasta ou área": "Setor privado",
        "Período": "-",
        "Temática principal": "Liberdade econômica, redução da máquina pública, combate a privilégios e reformas de mercado",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputado federal mais votado do RS em 2018 e reeleito em 2022",
    },
    "210002533584": {  # Paulo Pimenta (PT/RS)
        "Teve mandato antes de 2006?": "Vereador de Santa Maria (1989-1996); Deputado estadual RS (1999-2003); Deputado federal (2003-)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministro-Chefe da Secom; Ministro Extraordinário de Apoio à Reconstrução do RS",
        "Pasta ou área": "Comunicação Social / Apoio Emergencial RS",
        "Período": "2023-2024 (Secom), 2024 (Reconstrução RS)",
        "Temática principal": "Comunicação governamental, reconstrução de infraestrutura resiliente e agricultura familiar",
        "Fonte da informação": "Presidência da República / Câmara dos Deputados",
        "Observações": "Jornalista; deputado federal de múltiplos mandatos",
    },
    "210002543863": {  # Rigotto (RS - MDB)
        "Teve mandato antes de 2006?": "Deputado estadual RS (1979-1983); Deputado federal RS (1991-2003); Governador do Rio Grande do Sul (2003-2007)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente do Conselho de Desenvolvimento Econômico e Social do RS",
        "Pasta ou área": "Economia, Indústria e Tributação",
        "Período": "2003-2007",
        "Temática principal": "Reforma tributária (foi relator na Câmara), equilíbrio fiscal e atração de investimentos industriais",
        "Fonte da informação": "FGV CPDOC / Câmara dos Deputados",
        "Observações": "Advogado e cirurgião-dentista; liderança histórica do MDB",
    },
    "210002547816": {  # Sanderson (PL/RS)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Policial Federal (Escrivão de Polícia Federal); Presidente do Sindicato dos Policiais Federais do RS",
        "Pasta ou área": "Segurança Pública / Polícia Federal",
        "Período": "2003-2018",
        "Temática principal": "Segurança pública, fortalecimento das carreiras policiais e combate ao crime organizado",
        "Fonte da informação": "DPF / Câmara dos Deputados",
        "Observações": "Deputado federal desde 2019",
    },
    "240002541935": {  # Carlos Bolsonaro (PL/SC)
        "Teve mandato antes de 2006?": "Vereador do Rio de Janeiro (2001-2024)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Sem registros de cargos executivos",
        "Pasta ou área": "-",
        "Período": "-",
        "Temática principal": "Comunicação em redes sociais, pautas conservadoras e segurança pública",
        "Fonte da informação": "Câmara Municipal do Rio de Janeiro",
        "Observações": "Vereador da cidade do RJ por sete mandatos consecutivos",
    },
    "240002541931": {  # Caroline de Toni (PL/SC)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Advogada",
        "Pasta ou área": "Advocacia Privada",
        "Período": "2010-2018",
        "Temática principal": "Direito constitucional, garantias contra decisões judiciais monocráticas, agronegócio de SC",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Presidiu a CCJC da Câmara dos Deputados em 2024",
    },
    "260002547290": {  # André Moura (UNIÃO/SE)
        "Teve mandato antes de 2006?": "Prefeito de Pirambu SE (1997-2004)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário Chefe da Casa Civil do Estado do Rio de Janeiro; Secretário de Representação do Governo do RJ em Brasília",
        "Pasta ou área": "Casa Civil / Articulação Política",
        "Período": "2019-2020",
        "Temática principal": "Articulação política no Congresso (líder de governo na Câmara), gestão pública e infraestrutura",
        "Fonte da informação": "Diário Oficial do RJ / Câmara dos Deputados",
        "Observações": "Deputado estadual SE (2007-2011); Deputado federal (2011-2019)",
    },
    "260002549130": {  # Del. André David (REPUBLICANOS/SE)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Delegado da Polícia Civil de Sergipe; Diretor do Departamento de Narcóticos (Denarc-SE)",
        "Pasta ou área": "Segurança Pública / Polícia Judiciária",
        "Período": "2007-presente",
        "Temática principal": "Segurança pública, desarticulação do tráfico de drogas e combate à violência armada",
        "Fonte da informação": "Polícia Civil de Sergipe / SSP-SE",
        "Observações": "Delegado de carreira da Polícia Civil de Sergipe",
    },
    "260002549127": {  # Eduardo Amorim (REPUBLICANOS/SE)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Saúde de Sergipe",
        "Pasta ou área": "Saúde",
        "Período": "2003-2004",
        "Temática principal": "Saúde pública, medicina (médico anestesiologista), seguridade social e municipalismo",
        "Fonte da informação": "Senado Federal / Câmara dos Deputados",
        "Observações": "Deputado federal (2007-2011); Senador por Sergipe (2011-2019)",
    },
    "260002551550": {  # Edvaldo (PDT/SE)
        "Teve mandato antes de 2006?": "Vereador de Aracaju (1989-2000); Vice-prefeito de Aracaju (2001-2006)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Presidente da Frente Nacional de Prefeitos (FNP)",
        "Pasta ou área": "Gestão Municipal / Municipalismo",
        "Período": "2021-2024",
        "Temática principal": "Pacto federativo municipal, saúde pública (médico), saneamento básico e mobilidade",
        "Fonte da informação": "Frente Nacional de Prefeitos / Prefeitura de Aracaju",
        "Observações": "Prefeito de Aracaju por quatro mandatos (2006-2012, 2017-2024)",
    },
    "250002541308": {  # André do Prado (PL/SP)
        "Teve mandato antes de 2006?": "Vereador de Guararema (1993-1996); Vice-prefeito (1997-2000); Prefeito de Guararema (2001-2008)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário Municipal de Saúde de Guararema; Presidente da Alesp",
        "Pasta ou área": "Saúde / Poder Legislativo",
        "Período": "1990s (Saúde), 2023-presente (Alesp)",
        "Temática principal": "Saúde pública regional, apoio a hospitais filantrópicos e desenvolvimento de municípios paulistas",
        "Fonte da informação": "Assembleia Legislativa de São Paulo",
        "Observações": "Deputado estadual desde 2011; presidiu a Alesp",
    },
    "250002541312": {  # Guilherme Derrite (PP/SP)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Segurança Pública de São Paulo; Capitão da PM-SP (Rota)",
        "Pasta ou área": "Segurança Pública",
        "Período": "2023-presente (SSP-SP)",
        "Temática principal": "Segurança pública, enfrentamento ao crime organizado, operações policiais e inteligência",
        "Fonte da informação": "Diário Oficial de SP / Câmara dos Deputados",
        "Observações": "Oficial da reserva da PM-SP; deputado federal eleito em 2018 e 2022",
    },
    "250002551501": {  # Marina Silva (REDE/SP)
        "Teve mandato antes de 2006?": "Vereadora de Rio Branco (1989-1990); Deputada estadual AC (1991-1994); Senadora (1995-2011)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministra de Estado do Meio Ambiente e Mudança do Clima",
        "Pasta ou área": "Meio Ambiente e Mudança do Clima",
        "Período": "2003-2008, 2023-presente",
        "Temática principal": "Preservação da Amazônia, combate ao desmatamento, governança climática e sustentabilidade",
        "Fonte da informação": "Presidência da República / Senado Federal",
        "Observações": "Ambientalista e historiadora reconhecida internacionalmente; deputada federal eleita por SP em 2022",
    },
    "250002551502": {  # Simone Tebet (PSB/SP)
        "Teve mandato antes de 2006?": "Deputada estadual MS (2003-2004); Prefeita de Três Lagoas (2005-2010); Vice-governadora MS (2011-2014)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Ministra do Planejamento e Orçamento; Secretária de Governo de MS",
        "Pasta ou área": "Planejamento, Orçamento e Finanças",
        "Período": "2011-2013 (Governo MS), 2023-presente (Ministério do Planejamento)",
        "Temática principal": "Planejamento público estratégico, orçamento federal, responsabilidade fiscal e municipalismo",
        "Fonte da informação": "Ministério do Planejamento / Senado Federal",
        "Observações": "Professora de Direito; senadora por MS (2015-2023); 3ª colocada na eleição presidencial de 2022",
    },
    "270002548344": {  # Alexandre Guimarães (MDB/TO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Advogado e produtor rural",
        "Pasta ou área": "Agropecuária e Direito",
        "Período": "Setor privado",
        "Temática principal": "Agronegócio do Tocantins, regularização fundiária e logística de escoamento da produção",
        "Fonte da informação": "Câmara dos Deputados",
        "Observações": "Deputado federal eleito em 2022",
    },
    "270002548231": {  # Carlos Henrique Gaguim (UNIÃO/TO)
        "Teve mandato antes de 2006?": "Vereador de Palmas (1993-1996); Deputado estadual TO (1999-2010)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Governador do Tocantins (2009-2011 via eleição indireta); Presidente da Aleto",
        "Pasta ou área": "Governo Estadual / Poder Legislativo",
        "Período": "2009-2011",
        "Temática principal": "Infraestrutura rodoviária e energia, fortalecimento dos municípios e atração de empresas para o TO",
        "Fonte da informação": "FGV CPDOC / Câmara dos Deputados",
        "Observações": "Deputado federal desde 2015",
    },
    "270002548409": {  # Eli Borges (REPUBLICANOS/TO)
        "Teve mandato antes de 2006?": "Vereador de Palmas (1993-2002); Deputado estadual TO (2003-2018)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Pastor da Assembleia de Deus Madureira; Líder da Frente Parlamentar Evangélica",
        "Pasta ou área": "Liderança Religiosa e Comunitária",
        "Período": "1990-presente",
        "Temática principal": "Defesa da família e valores religiosos, agricultura familiar e assistência comunitária",
        "Fonte da informação": "Câmara dos Deputados / Assembleia TO",
        "Observações": "Deputado federal desde 2019",
    },
    "270002544629": {  # Paulo Mourão (PT/TO)
        "Teve mandato antes de 2006?": "Deputado federal constituinte (1989-1999); Prefeito de Porto Nacional (2005-2008); Deputado estadual TO (2015-2019)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado da Fazenda do Tocantins; Secretário Municipal de Infraestrutura de Palmas",
        "Pasta ou área": "Fazenda / Infraestrutura",
        "Período": "Anos 2000 / 2010",
        "Temática principal": "Agronomia, agricultura familiar, gestão fiscal e obras de infraestrutura no Tocantins",
        "Fonte da informação": "FGV CPDOC / Câmara dos Deputados / Assembleia TO",
        "Observações": "Engenheiro agrônomo; participou da Assembleia Nacional Constituinte de 1988",
    },
    "270002546038": {  # Ronaldo Dimas (PODE/TO)
        "Teve mandato antes de 2006?": "Deputado federal TO (2003-2007)",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Secretário de Estado das Cidades do Tocantins; Presidente do Instituto de Planejamento de Palmas; Prefeito de Araguaína (2013-2020)",
        "Pasta ou área": "Cidades, Habitação e Obras Públicas",
        "Período": "2011-2012 (Governo TO)",
        "Temática principal": "Planejamento urbano, drenagem, pavimentação e gestão de obras públicas",
        "Fonte da informação": "Câmara dos Deputados / Prefeitura de Araguaína",
        "Observações": "Engenheiro civil de formação; prefeito de Araguaína por dois mandatos",
    },
    "270002546039": {  # Vanderlei Luxemburgo (PODE/TO)
        "Teve mandato antes de 2006?": "Não",
        "Cargo não eletivo anterior (ex.: secretário de pasta)": "Treinador de futebol profissional (Seleção Brasileira e principais clubes); Empresário de comunicação (TV Jovem Palmas/SBT)",
        "Pasta ou área": "Esporte, Lazer e Comunicação",
        "Período": "1983-presente",
        "Temática principal": "Esporte como instrumento de inclusão social, turismo, comunicação regional e empreendedorismo",
        "Fonte da informação": "Imprensa nacional / Registro público",
        "Observações": "Cinco vezes campeão brasileiro de futebol; empresário do setor de radiodifusão no Tocantins",
    },
}
